### ISSUE TITLE
Split trees

### ISSUE THREAD

**Issue by dikastes** [Nathmel123/MEI-JSON#3]
For creating search indexes from MEI files, partial trees should be constructable from the main tree.

I'd like to be able to specify a set of splitting elements (say, in a config file). Once the parser hits such an element, it should retrieve its @xml:id and link this @xml:id in the main document instead of appending the subtree of the splitting element. Those subtrees should be processed individually and output in a custom file.

**Comment by Nathmel123** [comment]
Ich hätte da eine Frage...

**Comment by Nathmel123** [comment]
Hallo @dikastes

**Comment by dikastes** [comment]
reply from gmail

**Comment by Nathmel123** [comment]
Closed. See https://github.com/Nathmel123/MEI-JSON/pull/9.
