### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by dikastes** [Nathmel123/MEI-JSON#6]
Discard global variables and exotic property references.

- https://github.com/Nathmel123/MEI-JSON/commit/75c673a8dff92fe4475f7cd82d019b7e278aed1f#r138829420
- https://github.com/Nathmel123/MEI-JSON/commit/75c673a8dff92fe4475f7cd82d019b7e278aed1f#r138829497
- https://github.com/Nathmel123/MEI-JSON/commit/75c673a8dff92fe4475f7cd82d019b7e278aed1f#r138829599

**Comment by Nathmel123** [comment]
Already changed at branch [split_tree](https://github.com/Nathmel123/MEI-JSON/blob/split_tree/)
